module.exports= {
        name:{
            emptyText:"请输入用户名",
            reg:/^[a-zA-Z\u4e00-\u9fa5]{1}[a-zA-Z0-9_\u4e00-\u9fa5]{1,9}$/,
            errorText:"请输入正确格式的用户名",
            min:2,
            max:15,
            sizeText:"用户名长度必须大于等于2位小于等于11位"
        },
        email:{
            emptyText:"请输入邮箱",
            reg:/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,})$/,
            errorText:"请输入正确格式邮箱"
        },
        mobile:{
            emptyText:"请输入手机号",
            reg:/^1[3456789]\d{9}$/,
            errorText:"请输入正确格式手机号"
        },
        passwd:{
            emptyText:"请输入密码",
            reg:/^[\w-_]{6,16}$/,
            min:6,
            max:16,
            sizeText:"密码长度必须大于6位小于16位"
        },
        confirmPasswd:{
            emptyText:"请输入密码",
            reg:/^[\w-_]{6,16}$/,
            min:6,
            max:16,
            sizeText:"密码长度必须大于6位小于16位",
            isNotSameText:"两次输入的密码不一致"
        },
        idCard:{
            emptyText:"请输入身份证",
            reg:/^[1-9]\d{7}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}$|^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X)$/,
            errorText:"请输入正确格式的身份证号码",
            min:15,
            max:18,
            sizeText:"身份证号长度错误"
        },
        realName:{
            emptyText:"请输入姓名",
            reg:/^[\u4e00-\u9fa5]{1,}(\.)?[\u4e00-\u9fa5]{1,}$/,
            errorText:"请输入正确的姓名"
        },
        agencyName:{
          emptyText:"请填写房产经纪机构名称",
        },
        location:{
            emptyText:"请选择地址"
        },
        avatar:{
          emptyText:"请上传头像" 
        }
}