/**
 * 没有index 的不参与显示 或者另外需要进行处理
 */
module.exports={
    name:{
        label:"房屋标题",
        min:3,
        max:20,
        sizeText:"房产长度必须在3~30位之间",
        emptyText:"请输入房产名称",
        index:1
    },
    tradeType:{
        label:"房屋交易类型",
        emptyText:"请选择房产交易类型",
        options:[
          {label:"出租",value:2},
          {label:"出售",value:1},
        ],
        defaultValue:1,
        index:2
    },
    price:{
        label:"房产报价",
        emptyText:"请输入房产报价",
        min:0,
        max:Infinity,
        index:3,
    },
    images:{
      label:"房屋实景图",
      emptyText:"请上传房产实景图",
      min:1,
      max:5,
      sizeText:"房屋实景图最多上传5张",
      index:4,
    },
    area:{
      label:"房产面积",
      min:0,
      max:Infinity,
      emptyText:"请输入房产面积",
      index:5
    },
    beds:{
      label:"卧室数量",
      min:0,
      max:Infinity,
      emptyText:"请输入卧室数量",
      index:6
    },
    baths:{
      label:"卫生间数量",
      min:0,
      max:Infinity,
      emptyText:"请输入卧室数量",
      index:7
    },
    properties:{
      label:"房屋属性",
      minSize:1,
      emptyText:"请选择至少一样属性",
      options:[
          {label:"二手房",value:"ershou"},
          {label:"毛坯房",value:"maopi"},
          {label:"精装房",value:"jingzhuang"},
          {label:"小区房",value:"xiaoqu"},
          {label:"别墅",value:"bieshu"},
          {label:"村委房",value:"cunwei"},
          {label:"自建房",value:"zijian"},
          {label:"按揭房",value:"anjie"},
          {label:"集资房",value:"jizi"},
          {label:"学区房",value:"xuequ"},
      ],
      index:8
    },
    floorplans:{
      label:"房产平面图",
      emptyText:"请上传房产平面图",
      min:1,
      max:3,
      sizeText:"房屋平面图最多上传3张",
      index:9
    },
    location:{
        label:"房屋所在地",
        emptyText:"请选择房产",
        index:10
    },
    address:{
        label:"房屋详细地址",
        min:2,
        max:20,
        sizeText:"输入的地址长度必须在2~20字以内",
        emptyText:"请输入房产详细地址",
        index:11
    },
    tradeRelation:{    //交易关系
      label:"房屋交易关系",
      emptyText:"请选择房产持有类型",
      options:[
        {label:"代理交易",value:2},
        {label:"本人交易",value:1},
      ],
      defaultValue:1,
      index:12
    },
    remarks:{
        label:"房产描述",
        emptyText:"请输入房产描述",
        index:13,
    },
    tags:{
        label:"房产标签",
        emptyText:"请输入房产标签",
        index:14
    },
    state:{
        label:"交易状态",
        options:[
            {label:"待交易",value:1},
            {label:"下架",value:2},
        ],
        defaultValue:1,
        index:15
    },
    priceSort:{
      label:"价格排序",
      options:[
        {label:"从高到底",value:"price_desc"},
        {label:"从低到高",value:"price_asc"},
      ],
      defaultValue:"price_asc"
    },
    createTime:{
      label:"创建时间",
      index:16
    },
    updateTime:{
      label:"更新时间",
      index:17
    }
}