module.exports={
  idCard:{
    label:"身份证号码",
    emptyText:"请输入身份证",
    reg:/^[1-9]\d{7}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}$|^[1-9]\d{5}[1-9]\d{3}((0\d)|(1[0-2]))(([0|1|2]\d)|3[0-1])\d{3}([0-9]|X)$/,
    errorText:"请输入正确格式的身份证号码",
    min:15,
    max:18,
    sizeText:"身份证号长度错误"
  },
  realName:{
      label:"真实姓名",
      emptyText:"请输入姓名",
      reg:/^[\u4e00-\u9fa5]{1,}(\.)?[\u4e00-\u9fa5]{1,}$/,
      errorText:"请输入正确的姓名"
  },
  agencyName:{
    label:"经济机构名称",
    emptyText:"请填写房产经纪机构名称",
  },
  location:{
      label:"用户地址",
      emptyText:"请选择地址"
  },
  avatar:{
    label:"头像",
    emptyText:"请上传头像" 
  },
  authTime:{
    label:"认证时间",
    index:6
  },
  userType:{
    label:"用户类型",
    options:[
      {label:"普通用户",value:1},
      {label:"经纪人",value:2},
    ],
    defaultValue:1,
    index:2,
  },
}